# Generated by Django 2.0.3 on 2018-03-17 06:03

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='姓名')),
                ('ImagePath', models.CharField(blank=True, max_length=100, verbose_name='图片目录')),
                ('Description', DjangoUeditor.models.UEditorField(blank=True, verbose_name='描述')),
                ('Content', DjangoUeditor.models.UEditorField(default='test', verbose_name='内容')),
                ('initial_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
