# Generated by Django 2.0.3 on 2018-03-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='initial_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modify_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
