# Generated by Django 2.0.3 on 2018-03-17 09:01

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0002_auto_20180317_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=DjangoUeditor.models.UEditorField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='ImagePath',
            field=DjangoUeditor.models.UEditorField(verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='日志标题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='initial_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modify_time',
            field=models.DateField(auto_now=True),
        ),
    ]
