# Generated by Django 2.0.3 on 2018-03-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0003_auto_20180317_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Title', max_length=100)),
                ('ImagePath', models.CharField(default='', max_length=100)),
                ('Description', models.TextField(null=True)),
                ('Content', models.TextField(null=True)),
                ('Pub_time', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='initial_time',
        ),
    ]
