# Generated by Django 2.0.3 on 2018-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0005_auto_20180317_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='modify_day',
        ),
        migrations.AlterField(
            model_name='blog',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
