# Generated by Django 2.0.3 on 2018-04-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0007_auto_20180404_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
