# Generated by Django 2.0.3 on 2018-04-06 14:07

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0008_auto_20180406_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_log', '日志管理'), ('access_user_manage', '用户管理')),
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=DjangoUeditor.models.UEditorField(max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Name',
            field=DjangoUeditor.models.UEditorField(max_length=50, primary_key=True, serialize=False, verbose_name='日志标题'),
        ),
    ]
