# Generated by Django 2.0.3 on 2018-04-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0009_auto_20180406_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessControl',
        ),
    ]
