# Generated by Django 2.0.3 on 2018-04-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0012_auto_20180407_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='introduction',
        ),
    ]
