# Generated by Django 2.0.3 on 2018-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0013_remove_blog_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
