# Generated by Django 2.0.3 on 2018-04-07 13:54

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedAnt', '0016_blog_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='shortname',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=DjangoUeditor.models.UEditorField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Name',
            field=DjangoUeditor.models.UEditorField(primary_key=True, serialize=False, verbose_name='日志标题'),
        ),
    ]
